"""New Migration

Revision ID: 5d6ab7cd3626
Revises: 
Create Date: 2022-08-16 10:45:15.891802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6ab7cd3626'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ilcoord')
    op.drop_constraint('uzmanlar_id_key', 'uzman_list', type_='unique')
    op.create_index(op.f('ix_uzman_list_id'), 'uzman_list', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uzman_list_id'), table_name='uzman_list')
    op.create_unique_constraint('uzmanlar_id_key', 'uzman_list', ['id'])
    op.create_table('ilcoord',
    sa.Column('plaka', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('il_adi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('lon', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('northeast_lat', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('northeast_lon', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('southwest_lat', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('southwest_lon', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('plaka', name='ilcoord_pkey')
    )
    # ### end Alembic commands ###
